include $(WIND_KRNL_MK)/defs.layers.mk

KERNEL_PUBLIC_H_DIRS += h
BUILD_DIRS += src

ifdef _WRS_CONFIG_RTP
    USER_PUBLIC_H_DIRS += h
    BUILD_USER_DIRS += src
endif

include $(WIND_KRNL_MK)/rules.layers.mk
