#include <stdio.h>
#include <windows.h>
#include <ntstatus.h>

#define P(x) printf("%s %#x\n", #x, x)
#define D(x) printf("%s %p\n", #x, x)

void
PrintPreDefinedKeys(void)
{
	D(HKEY_CLASSES_ROOT);
	D(HKEY_CURRENT_CONFIG);
	D(HKEY_CURRENT_USER);
	D(HKEY_LOCAL_MACHINE);
	D(HKEY_PERFORMANCE_DATA);
	D(HKEY_USERS);

	P(KEY_ALL_ACCESS);
	P(KEY_CREATE_LINK);
	P(KEY_CREATE_SUB_KEY);
	P(KEY_ENUMERATE_SUB_KEYS);
	P(KEY_EXECUTE);
	P(KEY_NOTIFY);
	P(KEY_QUERY_VALUE);
	P(KEY_READ);
	P(KEY_SET_VALUE);
	P(KEY_WOW64_32KEY);
	P(KEY_WOW64_64KEY);
	P(KEY_WRITE);
}

void
PrintErrorCodes(void)
{
	P(STATUS_INVALID_IMAGE_FORMAT);
	P(STATUS_INVALID_IMAGE_NE_FORMAT);
	P(STATUS_INVALID_IMAGE_LE_FORMAT);
	P(STATUS_IMAGE_CHECKSUM_MISMATCH);
	P(STATUS_WX86_BREAKPOINT);
	P(STATUS_WX86_SINGLE_STEP);
}

void
PrintMemProtection(void)
{
	P(PAGE_EXECUTE);
	P(PAGE_EXECUTE_READ);
	P(PAGE_EXECUTE_READWRITE);
	P(PAGE_EXECUTE_WRITECOPY);
	P(PAGE_NOACCESS);
	P(PAGE_READONLY);
	P(PAGE_READWRITE);
	P(PAGE_WRITECOPY);
	P(PAGE_GUARD);
	P(PAGE_NOCACHE);
	P(PAGE_WRITECOMBINE);
}

void
PrintProcess(void)
{
	P(DELETE);
	P(READ_CONTROL);
	P(SYNCHRONIZE);
	P(WRITE_DAC);
	P(WRITE_OWNER);
	P(PROCESS_ALL_ACCESS);
	P(PROCESS_CREATE_PROCESS);
	P(PROCESS_CREATE_THREAD);
	P(PROCESS_DUP_HANDLE);
	P(PROCESS_QUERY_INFORMATION);
	P(PROCESS_QUERY_LIMITED_INFORMATION);
	P(PROCESS_SET_INFORMATION);
	P(PROCESS_SET_QUOTA);
	P(PROCESS_SUSPEND_RESUME);
	P(PROCESS_TERMINATE);
	P(PROCESS_VM_OPERATION);
	P(PROCESS_VM_READ);
	P(PROCESS_VM_WRITE);
	P(SYNCHRONIZE);
}

void
PrintRegValues(void)
{
	P(REG_BINARY);
	P(REG_DWORD);
	P(REG_DWORD_LITTLE_ENDIAN);
	P(REG_DWORD_BIG_ENDIAN);
	P(REG_EXPAND_SZ);
	P(REG_LINK);
	P(REG_MULTI_SZ);
	P(REG_NONE);
	P(REG_QWORD);
	P(REG_QWORD_LITTLE_ENDIAN);
	P(REG_SZ);
}

int
main(void)
{
	PrintPreDefinedKeys();
	PrintErrorCodes();
	PrintMemProtection();
	PrintProcess();
	PrintRegValues();
	return 0;
}
