#include "common.h"

#define P(x) printf("%-40s: %#x (%d)\n", #x, x, x)

void
status(void)
{
	P(TSS2_RC_SUCCESS);
	P(TPM2_RC_SUCCESS);
	P(TPM2_RC_RANGE);
	P(TPM2_RC_RETRY);
	P(TPM2_RC_MEMORY);
	P(TPM2_RC_HANDLE);
	P(TPM2_RC_AUTH_FAIL);
	P(TSS2_ESYS_RC_NO_ENCRYPT_PARAM);
	P(TSS2_ESYS_RC_MULTIPLE_DECRYPT_SESSIONS);
	P(TSS2_ESYS_RC_MULTIPLE_ENCRYPT_SESSIONS);
	P(TSS2_ESYS_RC_TRY_AGAIN);
	P(TSS2_ESYS_RC_INSUFFICIENT_RESPONSE);
	P(TSS2_ESYS_RC_RSP_AUTH_FAILED);
	P(TSS2_ESYS_RC_MALFORMED_RESPONSE);
	P(TSS2_ESYS_RC_MEMORY);
	P(TSS2_ESYS_RC_MULTIPLE_DECRYPT_SESSIONS);
	P(TSS2_ESYS_RC_MULTIPLE_ENCRYPT_SESSIONS);
	P(TSS2_ESYS_RC_BAD_TR);
	P(TSS2_ESYS_RC_NO_DECRYPT_PARAM);
	P(TSS2_ESYS_RC_BAD_REFERENCE);
	P(TSS2_BASE_RC_BAD_CONTEXT);
	P(TSS2_ESYS_RC_BAD_SEQUENCE);
	P(TSS2_ESYS_RC_MEMORY);
	P(TSS2_ESYS_RC_TRY_AGAIN);
	P(TSS2_ESYS_RC_INSUFFICIENT_RESPONSE);
	P(ESYS_TR_NONE);
	P(ESYS_TR_PASSWORD);
	P(ESYS_TR_RH_OWNER);
	P(ESYS_TR_RH_PLATFORM);
}

void
alg(void)
{
	P(TPM2_ALG_ERROR);
	P(TPM2_ALG_RSA);
	P(TPM2_ALG_SHA);
	P(TPM2_ALG_SHA256);
	P(TPM2_ALG_SHA384);
	P(TPM2_ALG_SHA512);
	P(TPM2_ALG_HMAC);
	P(TPM2_ALG_AES);
	P(TPM2_ALG_NULL);
	P(TPM2_ALG_FIRST);
	P(TPM2_ALG_LAST);
}

void
nvindex(void)
{
	P(TPM2_NV_INDEX_FIRST);
	P(TPM2_NV_INDEX_LAST);
}

int
main(void)
{
	status();
	nvindex();
	alg();

	return 0;
}
