#define STB_DS_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STB_TRUETYPE_IMPLEMENTATION
#define STB_SPRINTF_IMPLEMENTATION
#define STB_PERLIN_IMPLEMENTATION
#define STB_DIVIDE_IMPLEMENTATION
#define STB_DXT_IMPLEMENTATION
#define STB_IMAGE_RESIZE2_IMPLEMENTATION
#define STB_INCLUDE_IMPLEMENTATION
#include "stb_ds.h"
#include "stb_image.h"
#include "stb_image_write.h"
#include "stb_image_resize2.h"
#include "stb_dxt.h"
#include "stb_include.h"
#include "stb_truetype.h"
#include "stb_sprintf.h"
#include "stb_perlin.h"
#include "stb_divide.h"

